### PR TITLE
MNT: Re-rendered with conda-smithy 2.4.0

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi there,

Sorry I am not familiar with `conda-smithy` but I am in the need of `rpy2` built for `R-3.4.1`

Is there a way that I can help?

Best regards,
Sebastian

**Comment by bgruening** [comment]
@sebastian-luna-valero have a look at https://github.com/conda-forge/rpy2-feedstock/pull/2 for more information. It seems to crash under Windows and 3.4.1 - not sure how to solve it without a Windows computer. Or we skip it?

**Comment by sebastian-luna-valero** [comment]
Thanks @bgruening 

Skipping Windows is fine by me, what do @conda-forge/rpy2 contributors think?

**Comment by sebastian-luna-valero** [comment]
After having a look at `rpy2`'s recipe at [Continuum](https://anaconda.org/r/rpy2/files):
```
# This file created by conda-build 2.1.16
# meta.yaml template originally from:
# /home/rdonnelly/conda/conda-recipes/python/rpy2, last modified Tue Jul 25 18:21:08 2017
# ------------------------------------------------

package:
    name: rpy2
    version: 2.8.6
source:
    fn: rpy2-2.8.6.tar.gz
    patches:
        - 0001-ResetConsole_is_not_a_member_of_structRstart.patch
        - 0002-Win32__Add_missing_jump_to_toplevel___extern.patch
        - 0003-Win32__Fix_incorrect_type_of__buf__parameter_to_EmbeddedR_ReadConsole__.patch
        - 0004-Win32__Add_missing__include__stdlib_h_.patch
        - 0005-Win32__Hack_sysconfig_so_that__CC__is_set_to__gcc_.patch
        - 0006-Win32__Add___MINGW_USE_ANSI_STDIO_1_and__Wno-format_for___zd__in__rinterface_c.patch
        - 0007-Turn_off_some_pedantic_warnings__unused_variables_and_functions_.patch
        - 0008-Win32__Change_R_USER_check_for_HOMEDIR_to_HOMEDRIVE.patch
        - 0009-Win32__Use_get_R_HOME___if_R_HOME_is_not_set_.patch
        - 0110-52b73245e093d4cf32dfeb7c77e9f4da954316dc.patch
        - 0111-c090410d52149121083ce87387c93ea91514c39f.patch
    sha1: 1375b1c519d07c9fa9078eb45ca1ac518ae80c67
    url: https://bitbucket.org/rpy2/rpy2/get/RELEASE_2_8_6.tar.bz2
build:
    noarch: ''
    noarch_python: false
    number: '2'
    rpaths:
        - lib/R/lib/
        - lib/
    string: py36r3.4.1_2
requirements:
    build:
        - isl 0.12.2 0
        - libssh2 1.8.0 0
        - icu 54.1 0
        - fontconfig 2.12.1 3
        - krb5 1.13.2 0
        - jbig 2.1 0
        - cloog 0.18.0 0
        - harfbuzz 0.9.39 2
        - singledispatch 3.4.0.3 py36_0
        - r-base 3.4.1 0
        - zlib 1.2.8 3
        - pip 9.0.1 py36_1
        - ncurses 5.9 10
        - pcre 8.39 1
        - pango 1.40.3 1
        - sqlite 3.13.0 0
        - freetype 2.5.5 2
        - cairo 1.14.8 0
        - libiconv 1.14 0
        - gcc 4.8.5 7
        - glib 2.50.2 1
        - xz 5.2.2 1
        - setuptools 27.2.0 py36_0
        - libpng 1.6.27 0
        - jpeg 9b 0
        - tk 8.5.18 0
        - bzip2 1.0.6 3
        - gsl 2.2.1 0
        - libgcc 5.2.0 0
        - python 3.6.2 0
        - pixman 0.34.0 0
        - curl 7.54.1 0
        - gmp 6.1.0 0
        - libtiff 4.0.6 3
        - wheel 0.29.0 py36_0
        - mpc 1.0.3 0
        - libxml2 2.9.4 0
        - readline 6.2 2
        - six 1.10.0 py36_0
        - openssl 1.0.2l 0
        - mpfr 3.1.5 0
        - libffi 3.2.1 1
    run:
        - python
        - r-base
        - singledispatch
        - six
        - readline
        - libgcc
test:
    commands:
        - python -m rpy2.tests
    imports:
        - rpy2
        - rpy2.interactive
        - rpy2.interactive.tests
        - rpy2.ipython
        - rpy2.ipython.tests
        - rpy2.rinterface
        - rpy2.rinterface.tests
        - rpy2.rlike
        - rpy2.rlike.tests
        - rpy2.robjects
        - rpy2.robjects.lib
        - rpy2.robjects.lib.tests
        - rpy2.robjects.tests
    requires:
        - ipython
        - r-survival
        - r-ggplot2
        - r-dplyr
        - numpy
        - pandas
        - mock
about:
    home: http://rpy.sourceforge.net
    license: GNU General Public License v2 or later (GPLv2+)
    license_family: GPL
    summary: Python interface to the R language (embedded R)
extra:
    final: true
```

It looks like their recipe is much more comprehensive, and `conda-forge` is duplicating efforts. 

Why `conda-forge` doesn't just add those packages that are not already available in `defaults`?

**Comment by sebastian-luna-valero** [comment]
`rpy2 2.9.0` has been released:
https://bitbucket.org/rpy2/rpy2/downloads/?tab=tags
https://pypi.python.org/pypi/rpy2

Would it be possible to retry building `rpy2` here, please?

**Comment by bgruening** [comment]
@sebastian-luna-valero I guess this is more work as we likely need to update the patches.
I skiped windows for now here, so that we can go further at least for linux and osx. Then you can try to update the version?

**Comment by sebastian-luna-valero** [comment]
Sure, thanks @bgruening 

It looks like the `R-3.4.1` tests are failing due to `libgfortran` not present as a build dependency?

**Comment by bgruening** [comment]
@sebastian-luna-valero feel free to work on an update!

**Pull request merged**
