### PR TITLE
Update to 3.3.6

### PR DESCRIPTION
**Pull request by dbast**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Includes https://github.com/conda-forge/rpy2-feedstock/pull/69

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
@conda-forge/rpy2 Ready to merge. Thx.

**Comment by dbast** [comment]
Ping.

**Comment by angelito127** [comment]
I am trying to install a recent version (3.3x) of rpy2 and by following other web pages I arrived here. Could you let me know how to do it using conda? Thanks

**Pull request merged**
