### PR TITLE
Rebuild Againer

### PR DESCRIPTION
**Pull request by mariusvniekerk**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mariusvniekerk** [comment]
@conda-forge-admin please rerender

**Comment by croth1** [comment]
@mingwandroid, @mariusvniekerk  this is one of the few packages we have not yet ported to the new compiler infrastructure. From the massive work @mingwandroid had to put in to make it work previously, it seems that especially the Windows build will not be easy. Any idea how we can continue here?

**Comment by mariusvniekerk** [comment]
I'd probably recommend this as a starting base, and then moving it to rpy2>3,   Odds are a reasonable amount of the patches can be removed then.

**Comment by ocefpaf** [comment]
Let's go with https://github.com/conda-forge/rpy2-feedstock/pull/23

**Pull request closed without merging**
