### PR TITLE
Update recipe

### PR DESCRIPTION
**Pull request by ocefpaf**
Alternative for #9

### CODE REVIEW

**Comment by ocefpaf** [comment]
@isuruf it looks like of the flags is not OK during the `R CMD` part of the build:

```
-c: error: argument -h/--help: ignored explicit argument 'eaderpad_max_install_names'
```

As you can see all of my attempts to figure out where that is coming from failed :-(

Do you have any advice here? Without a Mac machine to iterate quickly this gets really annoying very fast :unamused:

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by halldc** [comment]
@bgruening @ocefpaf Looks like this is failing because `ggplot2 v2.2.1` isn't available for r35 builds, which is needed for testing
https://github.com/conda-forge/rpy2-feedstock/blob/master/recipe/meta.yaml#L56

**Comment by halldc** [comment]
@ocefpaf I think I understand the macOS error, but fixing it requires a new patch. The problem is that they use `argparse` to read the R config flags, but this fails when one of the flags starts with `-h`. This is easily fixed by removing the help option from the parser object.

```
diff --git a/setup.py b/setup.py
--- a/setup.py
+++ b/setup.py
@@ -271,7 +271,7 @@
     #lapacklibs = rexec.cmd_config('LAPACK_LIBS', True)
     #blaslibs = rexec.cmd_config('BLAS_LIBS', True)

-    parser = argparse.ArgumentParser()
+    parser = argparse.ArgumentParser(add_help=False)
     parser.add_argument('-I', action='append')
     parser.add_argument('-L', action='append')
     parser.add_argument('-l', action='append')
```

**Comment by ocefpaf** [comment]
> @bgruening @ocefpaf Looks like the Linux build is failing because `ggplot2 v2.2.1` isn't available for r35 builds, which is needed for testing
> [/recipe/meta.yaml@`master`#L56](https://github.com/conda-forge/rpy2-feedstock/blob/master/recipe/meta.yaml#L56)

Thanks for figuring this out @halldc. I see you are working on `ggplot`. I'll wait for it then.

**Pull request merged**
