### PR TITLE
rerender

### PR DESCRIPTION
**Pull request by ocefpaf**
To get this version with latest `r-base`. (I'll update the package version in another PR.)

### CODE REVIEW

**Comment by ocefpaf** [comment]
Windows is not happy with conda-forge's `r 3.4.1`

```
C:\bld\rpy2_1504043681031\_b_env\Library\mingw-w64\bin\gcc.exe -mdll -O -Wall -DMS_WIN64 -DWin32=1 -D__USE_MINGW_ANSI_STDIO=1 -DWin64=1 -DMS_WIN64=1 -I.\rpy\rinterface -IC:/bld/rpy2_1504043681031/_b_env/R/include -IC:/bld/rpy2_1504043681031/_b_env/R/include/x64 -IC:\bld\rpy2_1504043681031\_b_env\include -IC:\bld\rpy2_1504043681031\_b_env\include -c .\rpy\rinterface\_rinterface.c -o build\temp.win-amd64-3.6\Release\.\rpy\rinterface\_rinterface.o -m64 -Wno-unused-variable -Wno-unused-but-set-variable -Wno-unused-function
.\rpy\rinterface\_rinterface.c:73:29: fatal error: R_ext/eventloop.h: No such file or directory
compilation terminated.
error: command 'C:\\bld\\rpy2_1504043681031\\_b_env\\Library\\mingw-w64\\bin\\gcc.exe' failed with exit status 1
```

**Comment by bgruening** [comment]
@ocefpaf Oh sorry, only saw this now. I have opened a similar one. Do you think updating to the new version https://pypi.python.org/pypi/rpy2 is worth it.

I'm wondering what the strategy is with anacondarecipes, there are changes that are not in our branch:
https://github.com/conda-forge/rpy2-feedstock/compare/master...AnacondaRecipes:master

**Comment by bgruening** [comment]
From the release notes from R3.4: `Headers for Unix-only facilities ‘R_ext/GetX11Image.h’, ‘R_ext/QuartzDevice.h’ and ‘R_ext/eventloop.h’ are no longer installed on Windows.` Some problem exists with latest rpy2 version.

**Comment by ocefpaf** [comment]
@bgruening no problem. I can't really get back to this at the moment. So closing in favor of your PR.

**Pull request closed without merging**
